/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatIf: typeof import('./src/components/PhoneDisplay/ChatIf/index.vue')['default']
    ChatIfChat: typeof import('./src/components/PhoneDisplay/ChatIf/ChatIfChat.vue')['default']
    ChatIfMe: typeof import('./src/components/PhoneDisplay/ChatIf/ChatIfMe.vue')['default']
    ChatIfMoment: typeof import('./src/components/PhoneDisplay/ChatIf/ChatIfMoment.vue')['default']
    ChatIfUsers: typeof import('./src/components/PhoneDisplay/ChatIf/ChatIfUsers.vue')['default']
    EffectDisplay: typeof import('./src/components/EffectDisplay.vue')['default']
    GameScene: typeof import('./src/components/GameScene.vue')['default']
    ItemManage: typeof import('./src/components/ItemManage.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    PhoneDisplay: typeof import('./src/components/PhoneDisplay/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
